### PR TITLE
chore(deps): Symfony 7

### PR DESCRIPTION
**Pull request by mwansinck**
~Work in progress, currently trying it in our own Symfony projects~

- Allow Symfony 7
- Bumped minimum version of PHP
- Added missing dependencies

### CODE REVIEW

**Comment by jcrombez** [comment]
Hello,

I'm surprised someone else use this bundle :)
Thank you for trying to contribute i'll keep an eye on this.

**Comment by mwansinck** [comment]
@jcrombez We are running the datagrid-bundle on Symfony 7 without problems, did you took a look already?

**Comment by jcrombez** [comment]
Not yet, is it not a WIP anymore ?

**Comment by mwansinck** [comment]
> Not yet, is it not a WIP anymore ?

Hi, I removed the draft from the PR 3 weeks ago, should had also added a reply then to notify you, sorry. We are using the bundle in two (small) projects running on Symfony without any issues, could be we don't touch every functionality however.

**Comment by jcrombez** [comment]
We've not had to use SF7 yet so i'm not sure when i'll find the time to test this.
Do you know if it still work with the last SF6 ?

**Comment by mwansinck** [comment]
> We've not had to use SF7 yet so i'm not sure when i'll find the time to test this. Do you know if it still work with the last SF6 ?

Didn't test SF6 specifically, I am gonna do some checks. 

However, because I only modified some requirements in compose like Symfony **or Symfony 7**, and didn't had to do codechanges (besides a cleanup) I am sure the working of your bundle with Symfony 6 shouldn't be affected.

**Comment by jcrombez** [comment]
You're right, it should work, i merged it.
Thank you for contributing <3

**Pull request merged**
